### ISSUE TITLE
Documentation: Add some troubleshooting hints

### ISSUE THREAD

**Issue by grebaldi** [Inkdpixels/gulp-object-starter#8]
I had an error related to npm's lock files, when initially running npm install:

```
Error: EACCES, open '/home/wbehncke/.npm/_locks/lodash-eba9c9e29c2430bd.lock
```

These can be easily fixed with:

```
sudo chown -R $USER ~/.npm
sudo chown -R $USER /usr/local/lib/node_modules
```

It might make sense to state that in the README?

**Comment by Inkdpixels** [comment]
Are you sure this is an issue of this package and not of npm? 
I dont think it would make sense to have an extra F.A.Q. section directed to issues of npm/node, since these fixes can be easily found via google etc.

**Comment by grebaldi** [comment]
Yeah, you're right... Since this issue happened pretty isolatedly in context of this package - speaking of course of my environment exclusively - I thought it could help others to get started with it. But I see your point. I'll close this.

At least it gets mentioned in the issues now :D
